## Canary CI/CD
name: Canary
run-name: Canary

on:
  push:
    branches:
      - test-youtubeeducation

jobs:
  canary:
    if: ${{ github.actor != 'PlaykitJs-Bot' }}
    uses: kaltura/playkit-js-common/.github/workflows/canary_plugin.yaml@master
    secrets: inherit
    with:
      schema-type: "playerV3Versions"
      node-version: '18.x'
      tests-yarn-run-to-execute: 'build eslint flow test'
